### ISSUE TITLE
On chunked files post_process is being called multiple times

### ISSUE THREAD

**Issue by cadejager** [pftool/pftool#13] opened 2016-03-25 17:15 UTC
I think this is related to the hack we did to get it working before. The accumulator is called after each chunk finishes.

I found this by running a chunked transfer on a src that supports xattrs and then caught post_process() with gdb.

**Comment by jti-lanl** [comment] 2016-03-31 21:04
[I was going to try to reduce verbosity on github issues.  Sorry.]

I remember when we decided to add something like this snippet to worker_update_chunk():

```c
#if 1
        // once CTM is functional we think this code can be removed -- Chris DeJager
        // The problem is related to copying from sorce files that do not support
        // xattrs.
        else if (i == path_count-1) {
            get_output_path(out_node.path, base_path, &work_node, dest_node, o);
            update_stats(&work_node, &out_node);
        }
#endif
```

The point was to try to deal with CTM being non-functional on filesystems that don't support xattrs.  However, it is causing post_process() to get called multiple times (for each chunk written).

This in turn has the effect of removing the marfs_restart flag from the destination.  So, we can't tell when a chunked file is incomplete.  [The length of the file doesn't help, because post_process() sets that to the completed size.]

I think the problem is that path_count is not the right variable.  The number of paths doesn't necessarily match the number of chunks.  There's a variable chunk_count nearby, which appears correct on filesystems that do support xattrs, but in that case the question is moot.

What we ultimately need to do is develop our own hash-table in worker_update_chunk() and keep our own stats on files being chunked, and only call update_stats() when the last chunk has been written.   Gary suggests we store the bitmap for completed chunks in the MarFS MD file.  This would replace the CTM scheme of putting xattrs on source-files.  Alternatively, maybe we can fix the CTM logic so that it will realize when xattrs aren't working, and use files to hold the data, as was apparently the intention.  However, we should also switch to storing this on the destination-side.

But now that I think about this, I remember that we are already writing chunk-MD into the MarFS MD (destination) file.  And there are routines sitting around for counting how many chunks were written.  We could easily write others to figure out which ones weren't written. The CTM has extensibility to allow a custom scheme to be employed.  It might be simple if we could use our destination-side chunk-counting stuff as a simple CTM extension.

**Comment by garygrider** [comment] 2016-03-31 21:44
Seems to me we want to never consider using source side to keep track of anything as it could lead to the wrong answer if multiple people are copying the same source file etc.

FYI

**Comment by jti-lanl** [comment] 2016-03-31 22:24
I agree.  A secondary problem is that the source-side might be RO.

**Comment by brettkettering** [comment] 2016-04-13 21:13
Jeff is rearchitecting this in MarFS now and then this will be able to be fixed. We'll move this to Jeff now.

**Comment by brettkettering** [comment] 2016-04-13 21:20
It may be safest to use the $HOME/.pftool directory mechanism and not use xattrs because with the size of files we intend to handle, xattrs will not hold the amount of data we'd need to store.

**Comment by brettkettering** [comment] 2016-04-19 21:52
Understand the problem, but have not started. Time for implementation.

**Comment by jti-lanl** [comment] 2016-04-20 17:04
The changes in the master branch which converted "work_node" to "out_node" in worker_update_chunk() were committed 2015-08-25 (0ee9fe0eb66f4824696e8f80fd8b40c6ec0dd6b5).  This had the effect of moving the place where CTM xattrs were stored from the source-file to the dest-file.

Our merge in the "cpp" branch got the other parts of the commit, but not that part.  Fixing this now causes us (in the case where destination is not RO) to "correctly" manage CTM xattrs on the destination, and N:1 restarts with 'pftool -n' are now working.

TBD NEXT:  See whether we'll use files correctly, when xattrs are not available.

**Comment by jti-lanl** [comment] 2016-04-20 22:57
Fixed.

**Closed by jti-lanl** 2016-04-20 22:57 UTC
Labels: bug
